{
 "title": "网关日志分析",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "【接口维度】接口成功率（最近24小时）",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(1-(sum(increase(gateway_uri_http_response_count_total{status=~'5xx|4xx', uri!='notATargetUri'}[24h])) by (uri))/(sum(increase(gateway_uri_http_response_count_total{}[24h])) by (uri) >0 ))"
    },
    {
     "expr": "sum(increase(gateway_uri_http_response_count_total{status=~'5xx|4xx'}[24h])) by(uri)"
    }
   ]
  },
  {
   "title": "【接口维度】接口响应时间（最近24小时）",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(gateway_uri_http_response_time_seconds_sum[24h] )) by (uri) /(sum(increase(gateway_uri_http_response_time_seconds_count[24h]) ) by (uri)  > 10))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(gateway_uri_http_response_time_seconds_count[24h]) ) by (uri)  > 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "【平台维度】请求数变化趋势图",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(gateway_service_http_response_count_total[10m]))"
    }
   ]
  },
  {
   "title": "[平台维度]平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(gateway_service_http_response_time_seconds_sum[10m])) /( sum(increase(gateway_service_http_response_time_seconds_count[10m]))  > 5)"
    }
   ]
  },
  {
   "title": "[service维度]平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(gateway_service_http_response_time_seconds_sum[1h])) by(service)/( sum(increase(gateway_service_http_response_time_seconds_count[1h])) by (service) > 5)"
    }
   ]
  },
  {
   "title": "【service维度】累计请求数",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sort_desc(sum(gateway_service_http_response_count_total{service !=''}) by (service) >10)"
    }
   ]
  },
  {
   "title": "【service维度】请求数变化趋势图",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(increase(gateway_service_http_response_count_total[1m])) by(service)"
    }
   ]
  },
  {
   "title": "【servce维度】接口成功率 & 调用次数",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "1 - (sum(label_replace(increase(gateway_service_http_response_count_total{status='5xx'}[5m]), \"service\", \"$1-成功率\", \"service\",\"(.*)\")) by (service))/(sum(label_replace(increase(gateway_service_http_response_count_total{}[5m]), \"service\", \"$1-成功率\", \"service\",\"(.*)\")) by (service) >2 )"
    },
    {
     "expr": "sum(label_replace(increase(gateway_service_http_response_count_total[2m]), \"service\", \"$1-请求数\", \"service\",\"(.*)\")) by (service) > 2"
    }
   ]
  }
 ]
}